### ISSUE TITLE
【文档】缺少relatedList配置功能说明

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-website#157]
- 可以在整个对象中配置数组relatedList。
```
relatedList:
  - objectName: contacts
    columns:
      - name
      - title
      - mobile
      - email
    mobile_columns:
      - name
      - title
```
- 也可以配合`type: lookup`加上`relatedList: true`表示显示在子表中
```
  othercompany:
    type: lookup
    relatedList: true
    label: 签约对象
    searchable: true
    reference_to: accounts
    multiple: true
```

如果要保留`relatedList: true`的写法，需要说明下与直接配置`type: master_detail`的区别，否则至少文档中不要提及这种写法。
